/* Generated by pnpm brand:build from brand/tokens/tokens.json. */

export const BRAND = {
  blush: '#f3d0c5',
  ivory: '#fffaec',
  mint: '#bdd5ce',
  plum: '#6b5473',
} as const;

export const THEMES = {
  dark: {
    border: '#49414f',
    'border-strong': '#82718c',
    canvas: '#19171d',
    danger: '#f5b1b8',
    'event-blue': '#293950',
    'event-blue-edge': '#8daeda',
    'event-blush': '#472d31',
    'event-blush-edge': '#c68e86',
    'event-lilac': '#3c2e4a',
    'event-lilac-edge': '#b995cc',
    'event-mint': '#253d35',
    'event-mint-edge': '#689c83',
    fill: '#2a262f',
    focus: '#d6bde5',
    info: '#bcd4f4',
    'on-danger': '#47262c',
    'on-event-blue': '#cddef8',
    'on-event-blush': '#f3ccc6',
    'on-event-lilac': '#e4cef5',
    'on-event-mint': '#c6e8d7',
    'on-info': '#22334c',
    'on-primary': '#302238',
    'on-selection': '#e4d4ec',
    'on-success': '#1b3127',
    'on-warning': '#382b10',
    primary: '#cdb8d6',
    'primary-hover': '#dfcde6',
    selection: '#3d3046',
    success: '#b4d9c6',
    surface: '#242129',
    'surface-raised': '#2e2934',
    'surface-subtle': '#211e26',
    text: '#f5f0f5',
    'text-secondary': '#bbb0c1',
    warning: '#f1d38e',
  },
  light: {
    border: '#eeece7',
    'border-strong': '#948899',
    canvas: '#ffffff',
    danger: '#a13641',
    'event-blue': '#dae5f7',
    'event-blue-edge': '#7898c8',
    'event-blush': '#f6dad3',
    'event-blush-edge': '#bb7770',
    'event-lilac': '#e5dbee',
    'event-lilac-edge': '#9c7bae',
    'event-mint': '#d7eae0',
    'event-mint-edge': '#6c9c88',
    fill: '#f4f2ee',
    focus: '#85658e',
    info: '#315788',
    'on-danger': '#ffffff',
    'on-event-blue': '#315788',
    'on-event-blush': '#7b443e',
    'on-event-lilac': '#684b83',
    'on-event-mint': '#285a4a',
    'on-info': '#ffffff',
    'on-primary': '#ffffff',
    'on-selection': '#594263',
    'on-success': '#ffffff',
    'on-warning': '#ffffff',
    primary: '#584360',
    'primary-hover': '#4a3751',
    selection: '#eee7f1',
    success: '#285a4a',
    surface: '#ffffff',
    'surface-raised': '#ffffff',
    'surface-subtle': '#fcfbf9',
    text: '#302a34',
    'text-secondary': '#706875',
    warning: '#76520c',
  },
} as const;

export type ThemeScheme = keyof typeof THEMES;

export type ThemeColors = (typeof THEMES)['light'];

export const FONT_FAMILY = 'Inter';

export const TYPE_SCALE = {
  body: {
    lineHeight: 1.5,
    size: 14,
    weight: 400,
  },
  caption: {
    lineHeight: 1.4,
    size: 12,
    weight: 400,
  },
  display: {
    lineHeight: 1.1,
    size: 48,
    weight: 600,
  },
  heading: {
    lineHeight: 1.3,
    size: 20,
    weight: 600,
  },
  label: {
    lineHeight: 1.4,
    size: 13,
    weight: 500,
  },
} as const;

export const SPACING = [4, 8, 12, 16, 24, 32, 48, 64] as const;

export const RADIUS = {
  control: 8,
  event: 6,
  popover: 16,
  window: 18,
} as const;
