import { Buffer } from 'node:buffer';
import { execFileSync } from 'node:child_process';
import { cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';
import process from 'node:process';
import { fileURLToPath, URL } from 'node:url';
import { zipSync } from 'fflate';
import sharp from 'sharp';

const root = fileURLToPath(new URL('../../', import.meta.url));
const brand = join(root, 'brand');
const check = process.argv.includes('--check');
const sizes = [16, 20, 24, 32, 48, 64, 128, 256, 512, 1024];
const staging = await mkdtemp(join(tmpdir(), 'solunivo-brand-'));
const kit = join(staging, 'solunivo-brand-kit');

async function write(path, content) {
  await mkdir(join(path, '..'), { recursive: true });
  await writeFile(path, content);
}

function replaceOnce(source, pattern, replacement) {
  if ([...source.matchAll(new RegExp(pattern.source, 'g'))].length !== 1) {
    throw new Error(`The icon source no longer matches the iOS adapter: ${pattern}`);
  }
  return source.replace(pattern, replacement);
}

function iosArtwork(source) {
  // Fill a square before iOS applies its own mask. Keep the number and curl
  // curves intact; only the outer paper edges lose the baked-in macOS corners.
  let result = replaceOnce(source, /viewBox="0 0 1024 1024"/, 'viewBox="76 68 851 851"');
  result = replaceOnce(result, /transform="scale\(1\.02073\)"/, '');
  const cream = source.match(/id="solunivo-number-24-cream-face" d="[^"]*V483(C[^H]+)H258/);
  if (!cream) {
    throw new Error('The cream-face curl no longer matches the iOS adapter.');
  }
  const edges = {
    body: 'M76 68H927V919H76Z',
    'cream-face': `M76 68H927V483${cream[1]}H76Z`,
    'peach-face': 'M76 68H927V906H76Z',
  };
  for (const [name, path] of Object.entries(edges)) {
    const pattern = new RegExp(`<path\\b[^>]*id="solunivo-number-24-${name}"[^>]*>`);
    result = replaceOnce(result, pattern, (tag) => tag.replace(/\bd="[^"]*"/, `d="${path}"`));
  }
  return result;
}

function declarations(values, prefix = '') {
  return Object.entries(values)
    .map(([name, value]) => `  --${prefix}${name}: ${value.toLowerCase()};`)
    .join('\n');
}

function tokenCss(tokens) {
  return [
    '/* Generated by pnpm brand:build from brand/tokens/tokens.json. */',
    ':root {',
    declarations(tokens.brand, 'brand-'),
    '  --font-sans: Inter, -apple-system, BlinkMacSystemFont, sans-serif;',
    ...tokens.spacing.map((value) => `  --space-${value}: ${value}px;`),
    ...Object.entries(tokens.radius).map(([name, value]) => `  --radius-${name}: ${value}px;`),
    '}',
    ':root,',
    "[data-theme='light'] {",
    declarations(tokens.themes.light),
    '}',
    "[data-theme='dark'] {",
    declarations(tokens.themes.dark),
    '}',
    '',
  ].join('\n');
}

function luminance(color) {
  if (!/^#[\da-f]{6}$/i.test(color)) {
    throw new Error(`Expected an opaque six-digit hex color, got ${color}`);
  }
  const channels = [1, 3, 5].map(
    (index) => Number.parseInt(color.slice(index, index + 2), 16) / 255,
  );
  const [r, g, b] = channels.map((value) =>
    value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4,
  );
  return r * 0.2126 + g * 0.7152 + b * 0.0722;
}

function contrastReport(tokens) {
  const results = [];
  for (const [theme, colors] of Object.entries(tokens.themes)) {
    const pairs = [];
    for (const foreground of ['text', 'text-secondary']) {
      for (const background of ['canvas', 'surface', 'surface-subtle', 'surface-raised']) {
        pairs.push([foreground, background, 4.5]);
      }
    }
    pairs.push(
      ['on-primary', 'primary', 4.5],
      ['on-primary', 'primary-hover', 4.5],
      ['on-selection', 'selection', 4.5],
    );
    for (const color of ['mint', 'blush', 'lilac', 'blue']) {
      pairs.push([`on-event-${color}`, `event-${color}`, 4.5]);
    }
    for (const state of ['success', 'warning', 'danger', 'info']) {
      pairs.push([`on-${state}`, state, 4.5]);
    }
    for (const foreground of ['focus', 'border-strong']) {
      for (const background of ['surface', 'canvas', 'surface-raised']) {
        pairs.push([foreground, background, 3]);
      }
    }
    for (const [foreground, background, minimum] of pairs) {
      const [low, high] = [luminance(colors[foreground]), luminance(colors[background])].sort(
        (a, b) => a - b,
      );
      const ratio = (high + 0.05) / (low + 0.05);
      if (ratio < minimum) {
        throw new Error(`${theme}: ${foreground} on ${background} fails contrast`);
      }
      results.push({
        background,
        foreground,
        minimum,
        pass: true,
        ratio: Number(ratio.toFixed(2)),
        theme,
      });
    }
  }
  return results;
}

async function raster(svg, size, destination) {
  await write(destination, await sharp(svg, { density: 144 }).resize(size).png().toBuffer());
}

async function iconExports(appearance, filename) {
  const directory = join(kit, 'exports/icons', appearance);
  const source = join(brand, 'icons', filename);
  for (const size of sizes) {
    await raster(source, size, join(directory, `icon-${size}.png`));
  }
  const iconset = join(directory, 'Solunivo.iconset');
  await mkdir(iconset, { recursive: true });
  for (const size of [16, 32, 128, 256, 512]) {
    for (const scale of [1, 2]) {
      await cp(
        join(directory, `icon-${size * scale}.png`),
        join(iconset, `icon_${size}x${size}${scale === 2 ? '@2x' : ''}.png`),
      );
    }
  }
  execFileSync('iconutil', [
    '--convert',
    'icns',
    iconset,
    '--output',
    join(directory, 'Solunivo.icns'),
  ]);
}

async function collect(directory, entries = {}) {
  for (const item of (await readdir(directory, { withFileTypes: true })).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const path = join(directory, item.name);
    if (item.isDirectory()) {
      await collect(path, entries);
    } else if (item.isFile() && item.name !== '.DS_Store') {
      entries[`solunivo-brand-kit/${relative(kit, path).split('\\').join('/')}`] =
        await readFile(path);
    }
  }
  return entries;
}

try {
  if (process.platform !== 'darwin') {
    throw new Error(
      'Brand exports require macOS iconutil. App builds use committed icons and do not run this script.',
    );
  }
  await cp(brand, kit, { recursive: true });
  const tokens = JSON.parse(await readFile(join(brand, 'tokens/tokens.json'), 'utf8'));
  const css = tokenCss(tokens);
  await write(join(kit, 'tokens/tokens.css'), css);
  const contrast = contrastReport(tokens);
  await write(join(kit, 'tokens/contrast-report.json'), `${JSON.stringify(contrast, null, 2)}\n`);

  await iconExports('default', 'solunivo.svg');
  await iconExports('dark', 'solunivo-dark.svg');
  for (const file of await readdir(join(brand, 'logos'))) {
    if (file.endsWith('.svg')) {
      const png = await sharp(join(brand, 'logos', file), { density: 288 })
        .png()
        .toBuffer();
      await write(join(kit, 'exports/logos', file.replace('.svg', '.png')), png);
    }
  }
  const mono = await readFile(join(brand, 'icons/solunivo-monochrome.svg'), 'utf8');
  for (const [name, color] of [
    ['plum', '#6B5473'],
    ['black', '#000000'],
    ['white', '#FFFFFF'],
  ]) {
    const svg = mono.replaceAll('#6B5473', color);
    await write(join(kit, 'exports/monochrome', `mark-${name}.svg`), svg);
    for (const size of [16, 20, 24, 32, 40, 48, 64, 128, 512]) {
      await raster(
        Buffer.from(svg),
        size,
        join(kit, 'exports/monochrome', `mark-${name}-${size}.png`),
      );
    }
  }

  const source = await readFile(join(brand, 'icons/solunivo.svg'), 'utf8');
  const square = iosArtwork(source);
  const ios = await sharp(Buffer.from(square), { density: 144 })
    .resize(1024, 1024)
    .flatten({ background: tokens.brand.blush })
    .removeAlpha()
    .png()
    .toBuffer();
  await write(join(kit, 'exports/ios/icon.svg'), square);
  await write(join(kit, 'exports/ios/icon.png'), ios);

  const generated = new Map([
    [
      'apps/desktop/assets/icon.icns',
      await readFile(join(kit, 'exports/icons/default/Solunivo.icns')),
    ],
    ['apps/ios/assets/icon.png', ios],
    ['brand/tokens/tokens.css', Buffer.from(css)],
  ]);
  for (const [filename, content] of generated) {
    const target = join(root, filename);
    if (check) {
      const existing = await readFile(target);
      if (!existing.equals(content)) {
        throw new Error(`${filename} is stale. Run pnpm brand:build.`);
      }
    } else {
      await write(target, content);
    }
  }

  if (!check) {
    const output = join(root, 'output/branding');
    // A clean staging folder keeps stale alternatives out of the zip; the
    // published folder is replaced, not merged, for the same reason — a
    // copy on top of the previous build kept renamed or removed exports.
    const archive = zipSync(await collect(kit), {
      level: 6,
      mtime: new Date('2026-01-01T00:00:00Z'),
    });
    const published = join(output, 'solunivo-brand-kit');
    await rm(published, { force: true, recursive: true });
    await cp(kit, published, { recursive: true });
    await write(join(output, 'solunivo-brand-kit.zip'), archive);
  }
  process.stdout.write(
    `${check ? 'Verified' : 'Built'} app icons and brand tokens; ${contrast.length} contrast pairs pass.\n`,
  );
} finally {
  await rm(staging, { force: true, recursive: true });
}
