appId: com.solunivo.app
name: Accounts sheet opens and closes
tags:
  - ci
---
- runFlow: ../common/launch.yaml
- tapOn:
    id: 'open-settings'
- assertVisible: 'Accounts'
- assertVisible: 'Add Google Account'
- assertVisible:
    id: 'connect-contacts|contacts-connected'
- tapOn: 'Done'
- assertVisible: 'Today'
