appId: com.solunivo.app
name: Accounts sheet opens and closes
---
- launchApp
- tapOn:
    id: 'open-settings'
- assertVisible: 'Accounts'
- assertVisible: 'Add Google Account'
- tapOn: 'Done'
- assertVisible: 'Today'
